<a href="https://colab.research.google.com/github/Snehasrinekkalapudi/BASIC-ML/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


#Question 1
##Arithmetic Operations

In [6]:
a = np.array([4,5,6,8])
b = np.array([8,9,1,2])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulo division:",b%a)
print("Floor Division:",a//b)

Addition: [12 14  7 10]
Subtraction: [-4 -4  5  6]
Multiplication: [32 45  6 16]
Division: [0.5        0.55555556 6.         4.        ]
Modulo division: [0 4 1 2]
Floor Division: [0 0 6 4]


#Question 2
##Mean and Standard Deviation

In [9]:
a = np.array([2,3,4,5])
m = np.mean(a)
s = np.std(a)
print("Mean:",m)
print("Standard Deviation:",s)

Mean: 3.5
Standard Deviation: 1.118033988749895


#Question 3
##Array with step size of 5

In [10]:
a = np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


#Question 4
##Reshape array

In [13]:
a=np.arange(10,50,5)
r = a.reshape(2,4)
print(r)

[[10 15 20 25]
 [30 35 40 45]]


#Question 5
##Sub matrix and Replace values

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub = arr[1:,:2]
print("Sub-matrix:")
print(sub)
arr[arr>4] = 0
print("Rearranged array")
print(arr)

Sub-matrix:
[[4 5]
 [7 8]]
Rearranged array
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#Question 6
##1D arrays

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",np.add(a,b))
print("Multiplication:",np.multiply(a,b))
print("Division:",np.divide(a,b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


#Question 7
###Mean of each column
###Maximum value of array
###Sum of all *elements*

In [25]:
a=np.random.rand(4,4)
print("Mean of each column:")
print(np.mean(a,axis=0))
print("Maximum value of array:")
print(np.max(a))
print("Sum of all elements:")
print(np.sum(a))

Mean of each column:
[0.44599972 0.34329807 0.50466146 0.67479029]
Maximum value of array:
0.99729110250434
Sum of all elements:
7.8749981106036415


#Question 8
###Modify the array by adding 10 and multiply by 2

In [23]:
arr = np.array([1,2,3,4])
arr=(arr+10)*2
print(arr)

[22 24 26 28]


#Question 9
###Advanced slicing on 3D array

In [30]:
a=np.random.randint(1,100,size=(3,4,5))
print(a)
print("Second layer:",a[1])
print("First two rows and last three columns:",a[:,:2,-3:])
a[a%3==0]=-1
print("Modified array:",a)

[[[85 58 86 80 82]
  [19  7 39 79 42]
  [ 8 58 45 52 78]
  [47 19 15 91  7]]

 [[29 81 36  1 72]
  [59 17 80 35 87]
  [40 63 27 27 91]
  [76 79 75 81 88]]

 [[86 71 45 35 40]
  [59 90 85 34 40]
  [ 3  3 91 98 43]
  [72 96 57 69 53]]]
Second layer: [[29 81 36  1 72]
 [59 17 80 35 87]
 [40 63 27 27 91]
 [76 79 75 81 88]]
First two rows and last three columns: [[[86 80 82]
  [39 79 42]]

 [[36  1 72]
  [80 35 87]]

 [[45 35 40]
  [85 34 40]]]
Modified array: [[[85 58 86 80 82]
  [19  7 -1 79 -1]
  [ 8 58 -1 52 -1]
  [47 19 -1 91  7]]

 [[29 -1 -1  1 -1]
  [59 17 80 35 -1]
  [40 -1 -1 -1 91]
  [76 79 -1 -1 88]]

 [[86 71 -1 35 40]
  [59 -1 85 34 40]
  [-1 -1 91 98 43]
  [-1 -1 -1 -1 53]]]


#Question 10
###Perform broadcasting and advanced operations

In [38]:
a=np.random.randint(1,20,size=(3,3))
print(a)
r=np.mean(a,axis=1,keepdims=True)
n=a-r
print("Normalization:")
print(n)
s=a**2
print("Squared array:")
print(s)
t=np.argsort(a.ravel())[-3:]
print("Indices of top three vaues:")
print(t)


[[ 7  6  2]
 [19  1 10]
 [14 18 12]]
Normalization:
[[ 2.          1.         -3.        ]
 [ 9.         -9.          0.        ]
 [-0.66666667  3.33333333 -2.66666667]]
Squared array:
[[ 49  36   4]
 [361   1 100]
 [196 324 144]]
Indices of top three vaues:
[6 7 3]
